/**
 * Template Registry
 *
 * 30 premium brochure templates inspired by high-end UK estate agents.
 * Each template defines colors, fonts, and layout personality.
 * The page-layouts system uses these to generate Fabric.js canvas JSON.
 */

export interface BrochureTemplate {
  id: string;
  name: string;
  category: 'traditional-luxury' | 'modern-minimal' | 'editorial' | 'corporate-premium' | 'boutique-artisan' | 'heritage-classic';
  inspiration: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    backgroundAlt: string;
    text: string;
    textLight: string;
    headingColor: string;
  };
  fonts: {
    heading: string;
    body: string;
  };
  style: {
    headingWeight: string;
    headingCase: 'none' | 'uppercase' | 'capitalize';
    footerStyle: 'solid' | 'thin-line' | 'none' | 'gradient';
    topBarStyle: 'solid' | 'thin-line' | 'none';
    coverOverlay: 'dark' | 'light' | 'gradient-bottom' | 'none';
    coverTextPosition: 'bottom-center' | 'bottom-left' | 'center' | 'top-left';
    imageFrameStyle: 'none' | 'thin-border' | 'shadow';
    dividerStyle: 'line' | 'accent-block' | 'none' | 'dotted';
  };
  preview: {
    thumbnail: string; // CSS gradient for preview card
    description: string;
  };
}

export const templates: BrochureTemplate[] = [
  // ============================================
  // TRADITIONAL LUXURY (5)
  // ============================================
  {
    id: 'sir-classic',
    name: "Sotheby's Classic",
    category: 'traditional-luxury',
    inspiration: "Sotheby's International Realty",
    colors: {
      primary: '#002349',
      secondary: '#917035',
      accent: '#917035',
      background: '#F6F1F1',
      backgroundAlt: '#EDE8E4',
      text: '#002349',
      textLight: '#5A6B7D',
      headingColor: '#002349',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #002349, #917035)',
      description: 'Warm cream backgrounds, navy and gold palette, auction-house elegance',
    },
  },
  {
    id: 'glentree-prestige',
    name: 'Prestige Navy',
    category: 'traditional-luxury',
    inspiration: 'Glentree Estates',
    colors: {
      primary: '#1A2744',
      secondary: '#C8A96E',
      accent: '#C8A96E',
      background: '#FFFFFF',
      backgroundAlt: '#F5F3F0',
      text: '#2C2C2C',
      textLight: '#6B6B6B',
      headingColor: '#1A2744',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1A2744, #C8A96E)',
      description: 'Navy and gold, bold presence, established prestige',
    },
  },
  {
    id: 'warm-prestige',
    name: 'Warm Prestige',
    category: 'traditional-luxury',
    inspiration: 'Rokstone / SIR',
    colors: {
      primary: '#3D2B1F',
      secondary: '#C8A96E',
      accent: '#C8A96E',
      background: '#FAF7F2',
      backgroundAlt: '#F0EBE3',
      text: '#3D2B1F',
      textLight: '#7A6B5D',
      headingColor: '#3D2B1F',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'capitalize',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #3D2B1F, #C8A96E)',
      description: 'Warm brown and gold on cream, tactile luxury feel',
    },
  },
  {
    id: 'dark-luxury',
    name: 'Dark Luxury',
    category: 'traditional-luxury',
    inspiration: 'Ultra-prime market',
    colors: {
      primary: '#0D0D0D',
      secondary: '#C8A96E',
      accent: '#C8A96E',
      background: '#111111',
      backgroundAlt: '#1A1A1A',
      text: '#E8E8E8',
      textLight: '#999999',
      headingColor: '#FFFFFF',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'none',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #0D0D0D, #C8A96E)',
      description: 'Dark backgrounds with gold type, dramatic and exclusive',
    },
  },
  {
    id: 'ivory-gold',
    name: 'Ivory & Gold',
    category: 'traditional-luxury',
    inspiration: 'Premium country estates',
    colors: {
      primary: '#2C1810',
      secondary: '#B8960C',
      accent: '#B8960C',
      background: '#FFFEF8',
      backgroundAlt: '#F5F0E6',
      text: '#2C1810',
      textLight: '#8B7355',
      headingColor: '#2C1810',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'capitalize',
      footerStyle: 'thin-line',
      topBarStyle: 'thin-line',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'center',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #FFFEF8, #B8960C)',
      description: 'Ivory white with gold accents, refined country elegance',
    },
  },

  // ============================================
  // MODERN MINIMAL (5)
  // ============================================
  {
    id: 'foxtons-urban',
    name: 'Urban Teal',
    category: 'modern-minimal',
    inspiration: 'Foxtons',
    colors: {
      primary: '#017163',
      secondary: '#FFF000',
      accent: '#017163',
      background: '#FFFFFF',
      backgroundAlt: '#F5F5F5',
      text: '#1A1A1A',
      textLight: '#666666',
      headingColor: '#017163',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #017163, #FFF000)',
      description: 'Teal and gold, energetic urban feel, young London market',
    },
  },
  {
    id: 'geometric-grey',
    name: 'Geometric Grey',
    category: 'modern-minimal',
    inspiration: 'Marsh & Parsons',
    colors: {
      primary: '#1A2744',
      secondary: '#E8E8E8',
      accent: '#1A2744',
      background: '#FFFFFF',
      backgroundAlt: '#FAFAFA',
      text: '#333333',
      textLight: '#888888',
      headingColor: '#1A2744',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '600',
      headingCase: 'uppercase',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1A2744, #E8E8E8)',
      description: 'Grayscale minimalism, geometric sans-serif, ultra-restrained',
    },
  },
  {
    id: 'beauchamp-ultra',
    name: 'Ultra Minimal',
    category: 'modern-minimal',
    inspiration: 'Beauchamp Estates',
    colors: {
      primary: '#000000',
      secondary: '#C8A96E',
      accent: '#C8A96E',
      background: '#FFFFFF',
      backgroundAlt: '#FAFAFA',
      text: '#1A1A1A',
      textLight: '#999999',
      headingColor: '#000000',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '300',
      headingCase: 'uppercase',
      footerStyle: 'none',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'none',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #000000, #C8A96E)',
      description: 'Black and gold, extreme whitespace, gallery presentation',
    },
  },
  {
    id: 'digital-forward',
    name: 'Digital Blue',
    category: 'modern-minimal',
    inspiration: 'The House Partnership',
    colors: {
      primary: '#204CE5',
      secondary: '#112337',
      accent: '#204CE5',
      background: '#FFFFFF',
      backgroundAlt: '#F0F4FF',
      text: '#112337',
      textLight: '#5A6B7D',
      headingColor: '#112337',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #204CE5, #112337)',
      description: 'Vibrant blue, digital-first, contemporary and clean',
    },
  },
  {
    id: 'monochrome-lux',
    name: 'Monochrome',
    category: 'modern-minimal',
    inspiration: 'Minimalist luxury',
    colors: {
      primary: '#1A1A1A',
      secondary: '#C0C0C0',
      accent: '#C0C0C0',
      background: '#FFFFFF',
      backgroundAlt: '#F5F5F5',
      text: '#1A1A1A',
      textLight: '#777777',
      headingColor: '#000000',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '300',
      headingCase: 'uppercase',
      footerStyle: 'thin-line',
      topBarStyle: 'thin-line',
      coverOverlay: 'dark',
      coverTextPosition: 'center',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1A1A1A, #C0C0C0)',
      description: 'Pure black and white with silver accents, maximum restraint',
    },
  },

  // ============================================
  // EDITORIAL (5)
  // ============================================
  {
    id: 'dexters-magazine',
    name: 'Magazine Blue',
    category: 'editorial',
    inspiration: 'Dexters',
    colors: {
      primary: '#003366',
      secondary: '#DD3333',
      accent: '#DD3333',
      background: '#FFFFFF',
      backgroundAlt: '#F7F7F7',
      text: '#242424',
      textLight: '#666666',
      headingColor: '#003366',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #003366, #DD3333)',
      description: 'Blue and red editorial spreads, magazine feel',
    },
  },
  {
    id: 'christies-art',
    name: "Christie's Art",
    category: 'editorial',
    inspiration: "Christie's Real Estate",
    colors: {
      primary: '#1A1A2E',
      secondary: '#5F5DE4',
      accent: '#5F5DE4',
      background: '#F5F5FF',
      backgroundAlt: '#EEEEFC',
      text: '#1A1A2E',
      textLight: '#6B6B8D',
      headingColor: '#1A1A2E',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1A1A2E, #5F5DE4)',
      description: 'Lavender-white, asymmetric layouts, gallery-inspired',
    },
  },
  {
    id: 'tmh-architecture',
    name: 'Architecture',
    category: 'editorial',
    inspiration: 'The Modern House',
    colors: {
      primary: '#796D63',
      secondary: '#BBA67A',
      accent: '#BBA67A',
      background: '#FAF8F5',
      backgroundAlt: '#F0EDE8',
      text: '#2C2C2C',
      textLight: '#7A7268',
      headingColor: '#4A4238',
    },
    fonts: { heading: 'Inter', body: 'Playfair Display' },
    style: {
      headingWeight: '600',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #796D63, #BBA67A)',
      description: 'Earthy palette, architecture magazine aesthetic, design-led',
    },
  },
  {
    id: 'lifestyle-editorial',
    name: 'Lifestyle',
    category: 'editorial',
    inspiration: 'Premium lifestyle magazine',
    colors: {
      primary: '#2D2D2D',
      secondary: '#C4956A',
      accent: '#C4956A',
      background: '#FFFFFF',
      backgroundAlt: '#F9F6F2',
      text: '#2D2D2D',
      textLight: '#8B7D6B',
      headingColor: '#2D2D2D',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #2D2D2D, #C4956A)',
      description: 'Warm copper accents, lifestyle photography focus',
    },
  },
  {
    id: 'design-journal',
    name: 'Design Journal',
    category: 'editorial',
    inspiration: 'Architectural design press',
    colors: {
      primary: '#1C1C1C',
      secondary: '#E07A5F',
      accent: '#E07A5F',
      background: '#FFFFFF',
      backgroundAlt: '#F5F5F0',
      text: '#1C1C1C',
      textLight: '#6B6B6B',
      headingColor: '#1C1C1C',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '300',
      headingCase: 'uppercase',
      footerStyle: 'thin-line',
      topBarStyle: 'thin-line',
      coverOverlay: 'dark',
      coverTextPosition: 'top-left',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1C1C1C, #E07A5F)',
      description: 'Terracotta accents, technical precision, architectural focus',
    },
  },

  // ============================================
  // CORPORATE PREMIUM (5)
  // ============================================
  {
    id: 'kf-residential',
    name: 'Knight Frank Red',
    category: 'corporate-premium',
    inspiration: 'Knight Frank',
    colors: {
      primary: '#D50032',
      secondary: '#000000',
      accent: '#D50032',
      background: '#FFFFFF',
      backgroundAlt: '#F7F7F7',
      text: '#1A1A1A',
      textLight: '#666666',
      headingColor: '#1A1A1A',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'capitalize',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #D50032, #000000)',
      description: 'Signature red accents, structured grid, confident corporate',
    },
  },
  {
    id: 'savills-bold',
    name: 'Savills Bold',
    category: 'corporate-premium',
    inspiration: 'Savills',
    colors: {
      primary: '#CE171E',
      secondary: '#FFE850',
      accent: '#CE171E',
      background: '#FFFFFF',
      backgroundAlt: '#F5F5F5',
      text: '#1A1A1A',
      textLight: '#555555',
      headingColor: '#1A1A1A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'uppercase',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #CE171E, #FFE850)',
      description: 'Red and yellow colour blocking, bold corporate authority',
    },
  },
  {
    id: 'chestertons-purple',
    name: 'Purple Urban',
    category: 'corporate-premium',
    inspiration: 'Chestertons',
    colors: {
      primary: '#6B207D',
      secondary: '#3D1252',
      accent: '#6B207D',
      background: '#FFFFFF',
      backgroundAlt: '#F8F4FA',
      text: '#2C2C2C',
      textLight: '#777777',
      headingColor: '#3D1252',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '600',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #6B207D, #3D1252)',
      description: 'Distinctive purple branding, bold and contemporary London',
    },
  },
  {
    id: 'corporate-green',
    name: 'Corporate Green',
    category: 'corporate-premium',
    inspiration: 'Strutt & Parker / Knight Frank Green',
    colors: {
      primary: '#064F50',
      secondary: '#D50032',
      accent: '#064F50',
      background: '#FFFFFF',
      backgroundAlt: '#F0F5F5',
      text: '#1A1A1A',
      textLight: '#5A6B6B',
      headingColor: '#064F50',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #064F50, #D50032)',
      description: 'Teal green with red accent, structured and authoritative',
    },
  },
  {
    id: 'corporate-slate',
    name: 'Slate & Copper',
    category: 'corporate-premium',
    inspiration: 'Modern corporate property',
    colors: {
      primary: '#2F3640',
      secondary: '#C87533',
      accent: '#C87533',
      background: '#FFFFFF',
      backgroundAlt: '#F5F5F5',
      text: '#2F3640',
      textLight: '#7F8C8D',
      headingColor: '#2F3640',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '600',
      headingCase: 'uppercase',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #2F3640, #C87533)',
      description: 'Dark slate with copper accents, modern corporate edge',
    },
  },

  // ============================================
  // BOUTIQUE ARTISAN (5)
  // ============================================
  {
    id: 'winkworth-illustrated',
    name: 'Navy & Gold Cream',
    category: 'boutique-artisan',
    inspiration: 'Winkworth',
    colors: {
      primary: '#1C1C39',
      secondary: '#C18948',
      accent: '#C18948',
      background: '#FBF7F3',
      backgroundAlt: '#F3EDE5',
      text: '#1C1C39',
      textLight: '#6B6575',
      headingColor: '#1C1C39',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1C1C39, #C18948)',
      description: 'Navy and gold on warm cream, sophisticated and distinctive',
    },
  },
  {
    id: 'aston-chase-gallery',
    name: 'Rose Gallery',
    category: 'boutique-artisan',
    inspiration: 'Aston Chase',
    colors: {
      primary: '#000000',
      secondary: '#CD2653',
      accent: '#CD2653',
      background: '#DCD7CA',
      backgroundAlt: '#D0C9BB',
      text: '#6D6D6D',
      textLight: '#999999',
      headingColor: '#000000',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #DCD7CA, #CD2653)',
      description: 'Rose accent on warm beige, gallery-like curation',
    },
  },
  {
    id: 'tk-geometric',
    name: 'Orange Geometric',
    category: 'boutique-artisan',
    inspiration: 'TK International',
    colors: {
      primary: '#E85D26',
      secondary: '#3C1A4A',
      accent: '#E85D26',
      background: '#FFFFFF',
      backgroundAlt: '#FFF5F0',
      text: '#2C2C2C',
      textLight: '#777777',
      headingColor: '#3C1A4A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'uppercase',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #E85D26, #3C1A4A)',
      description: 'Bold orange and aubergine, geometric and warm',
    },
  },
  {
    id: 'artisan-craft',
    name: 'Artisan Earth',
    category: 'boutique-artisan',
    inspiration: 'Craft-quality boutique agents',
    colors: {
      primary: '#5C4033',
      secondary: '#8B7355',
      accent: '#8B7355',
      background: '#F5F0EB',
      backgroundAlt: '#EDE5DB',
      text: '#3C2F24',
      textLight: '#8B7D6B',
      headingColor: '#3C2F24',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'center',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'dotted',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #5C4033, #8B7355)',
      description: 'Earthy browns, organic textures, craft quality feel',
    },
  },
  {
    id: 'signature-teal',
    name: 'Signature Teal',
    category: 'boutique-artisan',
    inspiration: 'Independent boutique agents',
    colors: {
      primary: '#1A5653',
      secondary: '#D4A574',
      accent: '#D4A574',
      background: '#FFFFFF',
      backgroundAlt: '#F0F7F6',
      text: '#1A3330',
      textLight: '#5A7B78',
      headingColor: '#1A5653',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'thin-line',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1A5653, #D4A574)',
      description: 'Deep teal with warm copper, boutique personality',
    },
  },

  // ============================================
  // HERITAGE CLASSIC (5)
  // ============================================
  {
    id: 'sp-country',
    name: 'Country Green',
    category: 'heritage-classic',
    inspiration: 'Strutt & Parker',
    colors: {
      primary: '#2D5F2D',
      secondary: '#1A3A1A',
      accent: '#2D5F2D',
      background: '#FFFFFF',
      backgroundAlt: '#F2F5F0',
      text: '#2C2C2C',
      textLight: '#5A6B5A',
      headingColor: '#1A3A1A',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'capitalize',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #2D5F2D, #1A3A1A)',
      description: 'Heritage green, countryside photography, British tradition',
    },
  },
  {
    id: 'hamptons-warm',
    name: 'Hamptons Blue',
    category: 'heritage-classic',
    inspiration: 'Hamptons',
    colors: {
      primary: '#1B2A4A',
      secondary: '#FF6B5A',
      accent: '#FF6B5A',
      background: '#FFFFFF',
      backgroundAlt: '#FFF5F3',
      text: '#1B2A4A',
      textLight: '#5A6B8A',
      headingColor: '#1B2A4A',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'accent-block',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1B2A4A, #FF6B5A)',
      description: 'Deep blue with coral, warm and progressive heritage',
    },
  },
  {
    id: 'jackson-stops-estate',
    name: 'Burgundy Estate',
    category: 'heritage-classic',
    inspiration: 'Jackson-Stops',
    colors: {
      primary: '#8B1A1A',
      secondary: '#C8A96E',
      accent: '#8B1A1A',
      background: '#FFFFFF',
      backgroundAlt: '#FAF5F0',
      text: '#2C2C2C',
      textLight: '#7A6B5D',
      headingColor: '#8B1A1A',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '700',
      headingCase: 'capitalize',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #8B1A1A, #C8A96E)',
      description: 'Burgundy and gold, country house tradition, heraldic feel',
    },
  },
  {
    id: 'jdw-classic',
    name: 'Classic Green',
    category: 'heritage-classic',
    inspiration: 'John D Wood & Co.',
    colors: {
      primary: '#1B5E3B',
      secondary: '#C8A96E',
      accent: '#1B5E3B',
      background: '#FFFFFF',
      backgroundAlt: '#F5F8F5',
      text: '#1A1A1A',
      textLight: '#5A7B5A',
      headingColor: '#1B5E3B',
    },
    fonts: { heading: 'Playfair Display', body: 'Playfair Display' },
    style: {
      headingWeight: '700',
      headingCase: 'none',
      footerStyle: 'solid',
      topBarStyle: 'solid',
      coverOverlay: 'dark',
      coverTextPosition: 'bottom-center',
      imageFrameStyle: 'none',
      dividerStyle: 'line',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #1B5E3B, #C8A96E)',
      description: 'Dark green and gold, all-serif, English refinement',
    },
  },
  {
    id: 'country-manor',
    name: 'Country Manor',
    category: 'heritage-classic',
    inspiration: 'Rural country estates',
    colors: {
      primary: '#4A3728',
      secondary: '#8B7355',
      accent: '#8B7355',
      background: '#FBF8F3',
      backgroundAlt: '#F0EBE3',
      text: '#3C2F24',
      textLight: '#7A6B5D',
      headingColor: '#4A3728',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    style: {
      headingWeight: '400',
      headingCase: 'capitalize',
      footerStyle: 'thin-line',
      topBarStyle: 'none',
      coverOverlay: 'gradient-bottom',
      coverTextPosition: 'bottom-left',
      imageFrameStyle: 'thin-border',
      dividerStyle: 'dotted',
    },
    preview: {
      thumbnail: 'linear-gradient(135deg, #4A3728, #8B7355)',
      description: 'Warm earthy tones, landscape focus, tactile country feel',
    },
  },
];

export function getTemplateById(id: string): BrochureTemplate | undefined {
  return templates.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: BrochureTemplate['category']): BrochureTemplate[] {
  return templates.filter((t) => t.category === category);
}

export const templateCategories = [
  { id: 'traditional-luxury', label: 'Traditional Luxury', count: 5 },
  { id: 'modern-minimal', label: 'Modern Minimal', count: 5 },
  { id: 'editorial', label: 'Editorial', count: 5 },
  { id: 'corporate-premium', label: 'Corporate Premium', count: 5 },
  { id: 'boutique-artisan', label: 'Boutique Artisan', count: 5 },
  { id: 'heritage-classic', label: 'Heritage Classic', count: 5 },
] as const;
